### ISSUE TITLE
Release `0.2.0`

### ISSUE THREAD

**Issue by Nemo157** [swift-nav/clap-io#5]
The current change in master from #2 is a breaking change, so the version should be bumped to 0.2; it would be useful to actually release this to crates.io to make this crate usable again.

**Comment by pcrumley** [comment]
Thank you for pointing this out! We will release `v0.2.0` to crates.io as soon as this PR is merged: https://github.com/swift-nav/clap-io/pull/6

We will do our best to follow Semantic Versioning in the future

**Comment by pcrumley** [comment]
released `0.2.0` on crates.io

Thanks again for raising this issue!
